apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  addresses:
    # Virtual IP given by MetalLB by ARP
    # DHCP server from 192.168.1.33-199, but local network is /24, so 200-250 for MetalLB
    - 192.168.1.200-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - default-pool
  interfaces:
    - enp2s0
