apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  addresses:
    # Virtual IP given by MetalLB by ARP
    - 192.168.10.1-192.168.10.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - default-pool
  interfaces:
    - enp2s0
