{
 "title": "Argo CD",
 "tags": [ "argocd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Argo CD Status", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{health_status!=''Healthy''})",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(argocd_app_info{sync_status==''OutOfSync''})",
     "legendFormat": "Out of Sync"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "argocd_app_info" }
   ]
  }
 ]
}