apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: oidc-client-id
      remoteRef:
        key: /grafana/oidc-clientId
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: oidc-client-secret
      remoteRef:
        key: /grafana/oidc-clientSecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h
