apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
  - secretKey: admin-user
    remoteRef:
      key: grafana-admin-user
  - secretKey: admin-password
    remoteRef:
      key: grafana-admin-password
