apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
spec:
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-id
      remoteRef:
        key: /grafana/oidc-clientId
    - secretKey: oidc-client-secret
      remoteRef:
        key: /grafana/oidc-clientSecret
