apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-bot-credentials
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: telegram-bot-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: BOT_TOKEN
      remoteRef:
        key: /monitoring/telegram/BOT_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CHAT_ID
      remoteRef:
        key: /monitoring/telegram/CHAT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h
