apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-fitness-server-secrets
  namespace: sparky-fitness
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: sparky-fitness-server-secrets
    deletionPolicy: Retain
  data:
    - secretKey: SPARKY_FITNESS_API_ENCRYPTION_KEY
      remoteRef:
        key: /sparky-fitness/api-encryption-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JWT_SECRET
      remoteRef:
        key: /sparky-fitness/jwt-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SPARKY_FITNESS_ADMIN_EMAIL
      remoteRef:
        key: /sparky-fitness/admin-email
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h
