apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparky-fitness-server-backup-data
  namespace: sparky-fitness
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: zfs-generic-nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparky-fitness-server-uploads-data
  namespace: sparky-fitness
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: zfs-generic-nfs-csi
