apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sparky-fitness-server-backup-data
  namespace: sparky-fitness
spec:
  sourcePVC: sparky-fitness-server-backup-data
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: sparky-fitness-server-backup-data-restic-config
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sparky-fitness-server-uploads-data
  namespace: sparky-fitness
spec:
  sourcePVC: sparky-fitness-server-uploads-data
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: sparky-fitness-server-uploads-data-restic-config
    retain:
      daily: 7
      within: 3d
