apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-fitness-smtp
  namespace: sparky-fitness
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: sparky-fitness-smtp
    creationPolicy: Owner
  data:
    - secretKey: SPARKY_FITNESS_EMAIL_HOST
      remoteRef:
        key: /smtp/SMTP_HOST
    - secretKey: SPARKY_FITNESS_EMAIL_PORT
      remoteRef:
        key: /smtp/SMTP_PORT
    - secretKey: SPARKY_FITNESS_EMAIL_USER
      remoteRef:
        key: /smtp/SMTP_USER
    - secretKey: SPARKY_FITNESS_EMAIL_PASS
      remoteRef:
        key: /smtp/SMTP_PASSWORD
