apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-cnpg-cluster
spec:
  instances: 3
  storage:
    # Custom democratic-csi storage class
    storageClass: zfs-generic-nfs-csi
    size: 10Gi