provider:
  kubernetes:
    envoyService:
      # This sets the type of the data plane service to LoadBalancer.
      type: LoadBalancer
      annotations:
        # This tells MetalLB to assign a specific IP address. NOT WORKING
        metallb.io/load-balancer-ip: "192.168.1.201"
