database:
  provider: "postgres"

config:
  # -- Specifies whether a config map should be created.
  create: false

  audit:
    # -- User configured local IPv6 ranges for the audit log.
    localIPv6Ranges: ""

  ui:
    # -- Whether to enable default settings for the UI or allow customizations
    useDefaults: true

    settings:
      app:
        # -- The name of the application to be displayed in the UI
        appName: "Pocket ID"

        # -- Duration in minutes of a session before the user must sign in again
        sessionDuration: 60

        # -- Whether the user's email is pre-marked as verified for OIDC clients (typically used for testing)
        emailsVerified: false

        # -- Whether users can edit their own account details
        allowOwnAccountEdit: true

        # -- Whether to disable animations in the Admin UI
        disableAnimations: false

      smtp:
        # -- SMTP server hostname used to send outgoing emails
        host: ""

        # -- SMTP server port
        port: ""

        # -- Sender email address for outgoing emails
        from: ""

        # -- SMTP username for authentication
        user: ""

        # -- SMTP password for authentication
        password: ""

        # -- TLS option to use for SMTP. Options are 'none', 'starttls', or 'tls'
        tls: "none"

        # -- Whether to skip SMTP certificate verification (useful for self-signed certificates)
        skipCertVerify: false

      email:
        # -- Whether to send an email notification when a user logs in from a new device
        loginNotificationEnabled: false

        # -- Whether to allow admins to send one-time access sign-in links to the user's email
        oneTimeAccessAsAdminEnabled: false

        # -- Whether to allow unauthenticated users to request one-time access sign-in links sent to the user's email
        #    (note: this reduces security significantly, as anyone with email access can sign in)
        oneTimeAccessAsUnauthenticatedEnabled: false

      ldap:
        # -- Whether to enable LDAP authentication
        enabled: false

        # -- URL of the LDAP server
        url: ""

        # -- LDAP bind distinguished name (DN)
        bindDN: ""

        # -- LDAP bind password for authentication
        bindPassword: ""

        # -- LDAP search base DN for queries
        base: ""

        # -- LDAP user search filter (default is typically fine for most setups)
        userSearchFilter: "(objectClass=person)"

        # -- LDAP group search filter (default is typically fine for most setups)
        userGroupSearchFilter: "(objectClass=groupOfNames)"

        # -- Whether to skip LDAP certificate verification (useful for self-signed certificates)
        skipCertVerify: false

        attributes:
          user:
            # -- LDAP attribute for the unique identifier of the user
            uniqueIdentifier: ""

            # -- LDAP attribute for the username of the user
            username: ""

            # -- LDAP attribute for the email address of the user
            email: ""

            # -- LDAP attribute for the user's first name
            firstName: ""

            # -- LDAP attribute for the user's last name
            lastName: ""

            # -- LDAP attribute for the user's profile picture
            profilePicture: ""

          group:
            # -- LDAP attribute for querying group members
            member: "member"

            # -- LDAP attribute for the unique identifier of the group
            uniqueIdentifier: ""

            # -- LDAP attribute for the group's name
            name: ""

            # -- LDAP attribute for the admin group (used to assign Admin privileges)
            adminGroup: ""

secret:
  create: false
  name: pocket-id-db-credentials
