apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-config
  namespace: seaweedfs
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: adminAccessKey
      remoteRef:
        key: /seaweedfs/admin-access-key
    - secretKey: adminSecretKey
      remoteRef:
        key: /seaweedfs/admin-secret-key
    - secretKey: opencloudAccessKey
      remoteRef:
        key: /seaweedfs/opencloud-access-key
    - secretKey: opencloudSecretKey
      remoteRef:
        key: /seaweedfs/opencloud-secret-key
  target:
    name: seaweedfs-s3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        seaweedfs_s3_config: |
          {
            "identities": [
              {
                "name": "admin",
                "credentials": [
                  {
                    "accessKey": "{{ .adminAccessKey | toString }}",
                    "secretKey": "{{ .adminSecretKey | toString }}"
                  }
                ],
                "actions": ["Admin", "Read", "Write"]
              },
              {
                "name": "opencloud",
                "credentials": [
                  {
                    "accessKey": "{{ .opencloudAccessKey | toString }}",
                    "secretKey": "{{ .opencloudSecretKey | toString }}"
                  }
                ],
                "actions": ["Read:opencloud", "Write:opencloud"]
              }
            ]
          }
