apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hrld-data
  namespace: hrld
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
