apiVersion: v1
kind: Service
metadata:
  name: hrld
  namespace: hrld
  labels:
    app: hrld  # selected by the ServiceMonitor
spec:
  selector:
    app: hrld
  ports:
    - name: appservice
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
