apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden
        property: ADMIN_TOKEN
