apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: porkbun-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: porkbun-credentials
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: /porkbun/api-key
        property: apiKey
    - secretKey: secretApiKey
      remoteRef:
        key: /porkbun/secret-api-key
        property: secretApiKey
