apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.crds.yaml
  - cluster-issuer.yaml
  - externalsecret.yaml
  - webhook-rbac.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values/values.yaml
  # Chart is uploaded to dockerhub, (https://hub.docker.com/r/4ntb/porkbun-webhook/tags)
  # but kustomize doesn't allow oci artifacts yet...
  - name: ./charts/porkbun-webhook
    version: 0.1.0
    releaseName: cert-manager-webhook-porkbun
    namespace: cert-manager
    valuesFile: values/webhook-porkbun-values.yaml
    includeCRDs: true
