apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager


resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.crds.yaml
  - cluster-issuer.yaml
  - certificate.yaml
  - externalsecret.yaml

helmGlobals:
  # chartHome removed; using published Helm repo for porkbun-webhook

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values/values.yaml
  - name: cert-manager-webhook-porkbun
    repo: https://talinx.github.io/cert-manager-webhook-porkbun
    version: 0.1.0
    releaseName: cert-manager-webhook-porkbun
    valuesFile: values/webhook-porkbun-values.yaml
    includeCRDs: true
