apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.crds.yaml
  - cluster-issuer.yaml
  - externalsecret.yaml
  - webhook-rbac.yaml
  # Chart is uploaded to dockerhub, (https://hub.docker.com/r/4ntb/porkbun-webhook/tags)
  # but kustomize doesn't allow oci artifacts yet...
  # Instead, render helm chart to a yaml and apply that yaml:
  # helm template cert-manager-webhook-porkbun ./charts/porkbun-webhook
  # --version 0.1.0  --namespace cert-manager -f ./values/webhook-porkbun-values.yaml --include-crds > porkbun-webhook.yaml 2>&1
  - webhook.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values/values.yaml
