apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: porkbun-ddns-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: apiKey
      remoteRef:
        key: /porkbun/api-key
    - secretKey: secretApiKey
      remoteRef:
        key: /porkbun/secret-api-key

  target:
    name: porkbun-ddns-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        settings.json: |
          {
            "settings": [
              {
                "provider": "porkbun",
                "domain": "*.monederobox.dev",
                "api_key": "{{ .apiKey | toString }}",
                "secret_api_key": "{{ .secretApiKey | toString }}",
                "ip_version": "ipv4",
                "ipv6_suffix": ""
              }
            ]
          }