apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: readarr-config
spec:
  sourcePVC: readarr-config
  trigger:
    schedule: "0 2 * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 7
    repository: readarr-config-restic-config
    retain:
      daily: 7
      within: 3d
