---
# This ClusterRole contains all the permissions the VolSync operator controller needs to function.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsync-controller-role
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
      - volumesnapshots
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - volsync.backube
    resources:
      - replicationdestinations
      - replicationsources
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - volsync.backube
    resources:
      - replicationdestinations/status
      - replicationsources/status
    verbs:
      - get
      - patch
      - update
---
# This ClusterRoleBinding grants the permissions from the ClusterRole above
# to the VolSync ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volsync-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volsync-controller-role
subjects:
  - kind: ServiceAccount
    # IMPORTANT: Update the namespace and name if you installed VolSync differently.
    # This assumes the operator is in the 'volsync' namespace with a service account named 'volsync'.
    name: volsync
    namespace: volsync
