apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lidarr-config
spec:
  sourcePVC: lidarr-config
  trigger:
    schedule: "0 2 * * *"
  restic:
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
    pruneIntervalDays: 7
    cacheCapacity: 5Gi
    repository: lidarr-config-restic-config
    unlock: unlock
    retain:
      daily: 7
      within: 3d
