apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coredns
#helmCharts:
#  - name: coredns
#    repo: https://coredns.github.io/helm
#    releaseName: coredns
#    version: "1.42.4"
#    namespace: coredns
#    valuesFile: values/values.yaml
#    additionalValuesFiles:
#      - values/zones.yaml
