apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: democratic-csi

helmCharts:
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    releaseName: democratic-csi
    version: "0.15.0"
    namespace: democratic-csi
    valuesFile: values/values.yaml
