apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-cnpg-cluster
spec:
  instances: 3
  backup:
    barmanObjectStore:
      destinationPath: "hel1.your-objectstorage.com"
      s3Credentials:
        accessKeyId:
          name: hetzner-backup-bucket-credentials
          key: ACCESS_KEY
        secretAccessKey:
          name: hetzner-backup-bucket-credentials
          key: ACCESS_SECRET_KEY
  storage:
    # Custom democratic-csi storage class
    storageClass: zfs-generic-nfs-csi
    size: 10Gi
