apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infisical

resources:
  - infisical-db.yaml
  - httproute.yaml

helmCharts:
  - name: infisical-standalone
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    releaseName: infisical
    version: "1.6.1"
    namespace: infisical
    valuesFile: values/values.yaml
