# Necessary for ArgoCD installation, else init loop
preUpgradeChecker:
  # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
  jobEnabled: false
  # -- Setting that allows Longhorn to perform upgrade version checks after starting the Longhorn Manager DaemonSet Pods. Disabling this setting also disables `preUpgradeChecker.jobEnabled`. Longhorn recommends keeping this setting enabled.
  upgradeVersionCheck: true

persistence:
  # Default number of replicas for each volume.
  # With a 3-node cluster, 3 replicas is recommended for high availability.
  # This allows one node to fail without data loss.
  defaultClassReplicaCount: 3
  #
  # Data locality.
  # - disabled: a replica can be placed on any node.
  # - best-effort: Longhorn will try to keep a replica on the same node as the pod using the volume.
  # This is recommended for better performance.
  defaultDataLocality: best-effort

defaultSettings:
  #
  # Default path for storing data on each node.
  # It is highly recommended to change this to a dedicated disk for Longhorn.
  # For example: /mnt/longhorn-data
  defaultDataPath: /var/lib/longhorn-data/
  #
  # Number of replicas for each volume.
  # With a 3-node cluster, 3 replicas is recommended for high availability.
  # This allows one node to fail without data loss.
  defaultReplicaCount: \"\{"v1":"3","v2":"3"\}\"
  #
  # Allow scheduling on cordoned nodes.
  # This is useful for single-node clusters or for maintenance.
  disableSchedulingOnCordonedNode: false
  #
  # Storage over-provisioning percentage.
  # Set to 0 to disable over-provisioning.
  storageOverProvisioningPercentage: "0"
  #
  # Minimal available percentage of storage on a node.
  # If the available storage on a node is less than this, Longhorn will not schedule new replicas on it.
  storageMinimalAvailablePercentage: "10"
