preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: true

persistence:
  defaultClassReplicaCount: 3
  defaultDataLocality: "best-effort"

defaultSettings:
  defaultDataPath: "/var/lib/longhorn-data/"
  # Defaults to "{"v1":"3","v2":"3"}".
  #defaultReplicaCount: "3"

  # Scheduling settings
  disableSchedulingOnCordonedNode: "false"
  replicaSoftAntiAffinity: "true" # Allow replicas on same node if needed
  replicaAutoBalance: "best-effort" # Auto-balance replicas

  # Storage settings
  storageOverProvisioningPercentage: "0"
  storageMinimalAvailablePercentage: "10"
  storageReservedPercentageForDefaultDisk: "25" # Match your reserved space

  # Node scheduling
  allowVolumeCreationWithDegradedAvailability: "true" # Allow creation even if degraded

  # Replica settings
  replicaReplenishmentWaitInterval: "600" # Wait 10min before creating new replica
  concurrentReplicaRebuildPerNodeLimit: "5"
