---
# htpasswd secret for Docker CLI authentication
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-htpasswd
  namespace: zot
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: zot-htpasswd
    creationPolicy: Owner
  data:
    # htpasswd file content (bcrypt format)
    # Generate with: htpasswd -nbB <username> <password>
    - secretKey: htpasswd
      remoteRef:
        key: /zot/htpasswd
---
# OIDC credentials for PocketID authentication
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-oidc
  namespace: zot
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: zot-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Zot expects a JSON file with clientid and clientsecret
        credentials.json: |
          {
            "clientid": "{{ .clientId }}",
            "clientsecret": "{{ .clientSecret }}"
          }
  data:
    - secretKey: clientId
      remoteRef:
        key: /pocket-id/zot/CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: /pocket-id/zot/CLIENT_SECRET
