apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway

# Gateway API CRDs
resources: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml

helmCharts:
  - name: gateway-helm
    repo: oci://registry-1.docker.io/envoyproxy
    releaseName: envoy-gateway
    version: "v1.4.1"
    namespace: envoy-gateway
    valuesFile: values/values.yaml
