apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway

resources:
  # Gateway API CRDs
  # - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
  # For UDPRoute
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml
  # Envoy Gateway CRDs
  - https://github.com/envoyproxy/gateway/releases/download/v1.5.1/install.yaml
  - gateway-class.yaml
  - gateway.yaml
  - http-redirect-route.yaml

helmCharts:
  - name: gateway-helm
    repo: oci://registry-1.docker.io/envoyproxy
    releaseName: envoy-gateway
    version: "v1.5.1"
    namespace: envoy-gateway
    valuesFile: values/values.yaml
