apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway

helmCharts:
  - name: eg
    repo: oci://docker.io/envoyproxy/gateway-helm
    releaseName: envoy-gateway
    version: "v1.4.1"
    namespace: envoy-gateway
    valuesFile: values/values.yaml
