apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    releaseName: minio
    version: "8.0.10"
    namespace: minio
    valuesFile: values/values.yaml
