apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio
#helmCharts:
#  - name: minio
#    repo: https://charts.min.io/
#    releaseName: minio
#    version: "5.4.0"
#    namespace: minio
#    valuesFile: values/values.yaml
