apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: clientID
      remoteRef:
        key: /tailscale/oauth-client-id
    - secretKey: clientSecret
      remoteRef:
        key: /tailscale/oauth-client-secret
