apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: suwayomi-secrets
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: suwayomi-secrets
    deletionPolicy: Retain
  data:
    - secretKey: AUTH_PASSWORD
      remoteRef:
        key: /suwayomi/auth-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h
