servers:
  - zones:
      - zone: monederobox.dev.
    port: 53
    plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 10s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Required to query kubernetes API for data
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      #- name: prometheus
      #  parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: loop
      - name: log
      - name: reload
      - name: loadbalance
      - name: cache
        parameters: 30
      - name: template
        parameters: IN A monederobox.dev
        configBlock: |
          match ^([a-z0-9-]+)\.monederobox\.dev\.$
          answer "{{ .Name }} 60 IN A 10.10.10.10"
