servers:
  - zones:
    port: 53
    plugins:
      # --- Core utility plugins first ---
      - name: errors
      - name: health
        configBlock: |-
          lameduck 10s
      - name: ready
      - name: log

      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa

      # Get external node IP to always return and be dynamic
      - name: k8s_external
        parameters: monederobox.dev
      # Handle  custom zones before checking for anything else.
      #- name: template
      #  parameters: IN A monederobox.dev
      #  configBlock: |
      #    match ^([a-z0-9-]+)\.monederobox\.dev\.$
      #    answer "{{ .Name }} 60 IN A 10.10.10.10"

      # If it's not a custom zones, check if it's a Kubernetes service.
      #- name: kubernetes
      #  parameters: cluster.local in-addr.arpa ip6.arpa
      #  configBlock: |-
      #    pods insecure
      #    fallthrough in-addr.arpa ip6.arpa
      #    ttl 30

      # If nothing above has handled the request, forward it to an upstream resolver.
      - name: forward
        parameters: . /etc/resolv.conf

      # --- Other utility plugins ---
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
