apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-templater-db.yaml
  - secret-templater-smtp.yaml
  - kubernetes-secret-store.yaml
  - secret-reader-role.yaml
  - secret-reader-role-binding.yaml
  - secretstore-serviceaccount.yaml
