apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-smtp-credentials
  namespace: pocket-id
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: pocket-id-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        SMTP_FROM: "no-reply@pocket.id"
        SMTP_TLS: "false"
        SMTP_SKIP_CERT_VERIFY: "true"
  data:
    - secretKey: SMTP_HOST
      remoteRef:
        key: /smtp/SMTP_HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: /smtp/SMTP_PORT
    - secretKey: SMTP_USER
      remoteRef:
        key: /smtp/SMTP_USER
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: /smtp/SMTP_PASSWORD
