apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-db-connection
  namespace: pocket-id
spec:
  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore

  target:
    name: pocket-id-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_STRING: "{{ .uri | toString }}"

  data:
    - secretKey: uri
      remoteRef:
        key: pocket-id-cnpg-cluster-app
        property: uri
