apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencloud

resources:
  - httproute.yaml

helmGlobals:
  chartHome: charts
helmCharts:
  - name: opencloud
    valuesFile: values/values.yaml
    releaseName: opencloud
    namespace: opencloud

patches:
  - patch: |-
      spec:
        template:
          spec:
            containers:
              - name: opencloud
                env:
                  - name: PROXY_OIDC_REWRITE_WELLKNOWN
                    value: "false"
    target:
      kind: Deployment
      name: opencloud
