apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencloud

resources:
  - httproute.yaml

helmGlobals:
  chartHome: charts
helmCharts:
  - name: opencloud
    valuesFile: values/values.yaml
    releaseName: opencloud
    namespace: opencloud

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/24/value
        value: "false"
    target:
      kind: Deployment
      name: opencloud
