infisical:
  enabled: true
  image:
    repository: infisical/infisical
    tag: "v0.147.1"
    pullPolicy: "IfNotPresent"

redis:
  enabled: true
  auth:
    password: "niuZi5UElW"
  master:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
    extraInitContainers:
      - name: fix-aof
        image: redis:7
        command:
          - sh
          - -c
          - |
            for f in /data/appendonly.aof.*.incr.aof; do
              [ -f "$f" ] || continue
              echo "[fix-aof] checking $f"
              yes | redis-check-aof --fix "$f" || true
            done
        volumeMounts:
          - name: redis-data
            mountPath: /data

ingress:
  enabled: false
  nginx:
    enabled: false

postgresql:
  enabled: false
  fullnameOverride: ""
  name: ""
  useExistingPostgresSecret:
    # -- Set to true if using an existing Kubernetes secret that contains PostgreSQL connection string
    enabled: true
    existingConnectionStringSecret:
      # -- Kubernetes secret name containing the PostgreSQL connection string
      # Auto-generated secret by CNPG
      name: "infisical-cnpg-cluster-app"
      # -- Key name in the Kubernetes secret that holds the connection string
      key: "uri"

# Additional explicit disabling of PostgreSQL components
databaseSchemaMigrationJob:
  enabled: false
