infisical:
  enabled: true
  image:
    repository: infisical/infisical
    tag: "v0.131.0-postgres"
    pullPolicy: "Always"

ingress:
  enabled: false
  nginx:
    enabled: false

postgresql:
  enabled: false
  useExistingPostgresSecret:
    # -- Set to true if using an existing Kubernetes secret that contains PostgreSQL connection string
    enabled: true
    existingConnectionStringSecret:
      # -- Kubernetes secret name containing the PostgreSQL connection string
      name: ""
      # -- Key name in the Kubernetes secret that holds the connection string
      key: ""