apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snapshot-controller

resources:
  # Install volume snapshot CRDs
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd

helmCharts:
  - name: snapshot-controller
    repo: https://democratic-csi.github.io/charts/
    releaseName: snapshot-controller
    version: "0.3.0"
    namespace: kube-system
