apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-oidc-secret
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: karakeep-oidc
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: /pocket-id/karakeep/OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: /pocket-id/karakeep/OAUTH_CLIENT_SECRET
    - secretKey: OPENAPI_KEY
      remoteRef:
        key: /karakeep/OPENAPI_KEY
