apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: karakeep-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: /pocket-id/karakeep/OAUTH_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: /pocket-id/karakeep/OAUTH_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: /karakeep/OPENAPI_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: /karakeep/NEXTAUTH_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h
