apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: karakeep-secrets
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: /pocket-id/karakeep/OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: /pocket-id/karakeep/OAUTH_CLIENT_SECRET
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: /karakeep/OPENAPI_KEY
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: /karakeep/NEXTAUTH_SECRET
