apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-reader-binding
  namespace: pocket-id
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-reader
subjects:
  - kind: ServiceAccount
    name: external-secrets # The SA used by the ClusterSecretStore
    namespace: external-secrets # The namespace of the SA
