apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-secret-store
  namespace: pocket-id
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: pocket-id
      auth:
        serviceAccount:
          name: pocket-id-secretstore-sa
          namespace: pocket-id
