apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-secret-store
  namespace: pocket-id
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: pocket-id-secretstore-sa
          namespace: pocket-id
