apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pocket-id

resources:
  - pocket-id-db.yaml
  - pocket-id-backup.yaml
  - secret-templater-db.yaml
  - kubernetes-secret-store.yaml
  - secret-reader-role.yaml
  - secret-reader-role-binding.yaml
  - secretstore-serviceaccount.yaml
  - cnpg-secret-reader-role-binding.yaml

helmCharts:
  - name: pocket-id
    repo: https://anza-labs.github.io/charts
    releaseName: pocket-id
    version: "1.5.4"
    namespace: pocket-id
    valuesFile: values/values.yaml
