apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-db-connection
  namespace: pocket-id # Make sure this is the namespace pocket-id is in
spec:
  secretStoreRef:
    # Pointing back to the ClusterSecretStore
    name: kubernetes-cluster-store
    kind: ClusterSecretStore

  # This is the secret that will be CREATED for your Helm chart to use
  target:
    name: pocket-id-db-credentials # Assumed name, change if your chart needs another name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Create a key named DB_CONNECTION_STRING with the value from .uri
        DB_CONNECTION_STRING: "{{ .uri | toString }}"

  # This is the source data to be fetched
  data:
    - secretKey: uri # This is the name for the template variable above
      remoteRef:
        key: pocket-id/pocket-id-cnpg-cluster-app # The source secret from CNPG
        property: uri # The key within that source secret
