apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-secrets
  namespace: navidrome
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: navidrome-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ND_LASTFM_APIKEY
      remoteRef:
        key: /navidrome/ND_LASTFM_APIKEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ND_LASTFM_SECRET
      remoteRef:
        key: /navidrome/ND_LASTFM_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ND_SPOTIFY_ID
      remoteRef:
        key: /navidrome/ND_SPOTIFY_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ND_SPOTIFY_SECRET
      remoteRef:
        key: /navidrome/ND_SPOTIFY_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h
