apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: navidrome
  namespace: navidrome
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - "navidrome.monederobox.dev"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: navidrome
          port: 4533
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
