apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claude-auth
  namespace: loomie
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: claude-auth
    creationPolicy: Owner
  data:
    # Claude Code OAuth token (used via CLAUDE_CODE_OAUTH_TOKEN env var)
    - secretKey: oauth-token
      remoteRef:
        key: /loomie/CLAUDE_CODE_OAUTH_TOKEN
