apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-secret-store
spec:
  provider:
    infisical:
      hostAPI: "http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080"
      auth:
        universalAuthCredentials:
          clientId:
            secretRef:
              name: infisical-credentials-secret
              key: clientId
              namespace: external-secrets
          clientSecret:
            secretRef:
              name: infisical-credentials-secret
              key: token
              namespace: external-secrets
