apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-secret-store
spec:
  provider:
    infisical:
      hostAPI: "http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080"
      secretsScope:
        projectSlug: prod
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-credentials-secret
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: infisical-credentials-secret
            namespace: external-secrets
            key: token
