apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-cluster-store
spec:
  provider:
    # This provider allows fetching secrets from the Kubernetes API
    kubernetes:
      server:
        # Connect to the local Kubernetes cluster
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
      auth:
        # Use the service account of the External Secrets Operator
        serviceAccount:
          name: external-secrets # This might vary based on your ESO installation
          namespace: external-secrets # This is the namespace where ESO is installed
