apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - clustersecretstore.yaml
  - kube-cluster-secret-store.yaml
  - kube-clusterstore-role.yaml
  - kube-clusterstore-role-binding.yaml
  - kube-clusterstore-sa.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.18.2
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values/values.yaml
