apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-secrets
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: slskd-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SLSK_USERNAME
      remoteRef:
        key: /slskd/slsk-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SLSK_PASSWORD
      remoteRef:
        key: /slskd/slsk-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JWT_KEY
      remoteRef:
        key: /slskd/jwt-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h
