apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-secrets
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: slskd-secrets
    creationPolicy: Owner
  data:
    - secretKey: SLSK_USERNAME
      remoteRef:
        key: /slskd/slsk-username
    - secretKey: SLSK_PASSWORD
      remoteRef:
        key: /slskd/slsk-password
    - secretKey: JWT_KEY
      remoteRef:
        key: /slskd/jwt-key
    - secretKey: API_KEY
      remoteRef:
        key: /slskd/api-key
