apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: slskd
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - httproute.yaml
  - oidc-secret.yaml
  - externalsecret.yaml
  - config-secret.yaml
  - restic-config.yaml
  - replicationsource.yaml
