apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-oidc-secret
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: slskd-oidc-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-secret: "{{ .client_secret }}"
  data:
    - secretKey: client_secret
      remoteRef:
        key: /pocket-id/slskd/OAUTH_CLIENT_SECRET
