redis-ha:
  enabled: true

# We terminate TLS at the gateway
configs:
  params:
    server.insecure: true
  cm:
    url: https://argocd.monederobox.dev
    oidc.config: |
      name: PocketID
      issuer: https://pocket-id.monederobox.dev
      clientID: $argocd-secret:oidc.clientId
      clientSecret: $argocd-secret:oidc.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
  rbac:
    policy.csv: |
      g, ArgoCDAdmins, role:admin

controller:
  replicas: 1
  metrics:
    enabled: true

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicas: 2
