redis-ha:
  enabled: true

# We terminate TLS at the gateway
configs:
  params:
    server.insecure: true

controller:
  replicas: 1

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicas: 2
