apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
spec:
  parentRefs:
    - name: envoy-gateway
  hostnames:
    - "argocd.monederobox.dev"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
