apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - httproute-internal.yaml
  - externalsecret.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    version: "8.6.0"
    namespace: argocd
    valuesFile: values/values.yaml
