apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valheim-secrets
  namespace: valheim
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: valheim-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SERVER_PASS
      remoteRef:
        key: /valheim/SERVER_PASS
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  refreshInterval: 1h